# Generated by Django 5.2.1 on 2025-05-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0003_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=True),
        ),
    ]
