# Generated by Django 5.2.1 on 2025-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0004_alter_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
