# Generated by Django 5.2.1 on 2025-05-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
