# Generated by Django 5.2.1 on 2025-06-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0008_productrating_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
